from lazerpay.resource import LazerPayClient
from myshop.settings import *


lazerpay = LazerPayClient(pubKey=LAZER_PUBLIC_KEY, secretKey=LAZER_SECRET_KEY)


'''
Initialize payment
'''

try:
    response = lazerpay.initTransaction( 
        reference="YOUR_REFERENCE", # Replace with a reference you generated
        amount="10", 
        customer_name="Njoku Emmanuel", 
        customer_email="kalunjoku123@gmail.com", 
        coin="USDC", 
        currency="NGN", 
        accept_partial_payment=True # By default, it's false
    )
except Exception as e:
    raise e

'''
Confirm Payment
'''
try:
    response = lazerpay.confirmPayment(
        identifier="address generated or the reference generated by you from initializing payment"
    )
except Exception as e: 
    raise e

'''
Get Accepted Coins
'''
try:
    response = lazerpay.getAcceptedCoins()
except Exception as e: 
    raise e

'''
Payout
'''
try:
    response = lazerpay.payout(amount=1,
            recipient="0x0B4d358D349809037003F96A3593ff9015E89efA", 
            coin="BUSD", 
            blockchain="Binance Smart Chain"
        )
except Exception as e: 
    raise e