# Generated by Django 4.0.3 on 2022-05-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayWithCrypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.PositiveBigIntegerField()),
                ('currency', models.CharField(max_length=225)),
                ('reference', models.CharField(max_length=25)),
                ('successful', models.BooleanField(default=False)),
            ],
        ),
    ]
