# Generated by Django 4.0.3 on 2022-05-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paywithcrypto',
            name='coin',
            field=models.CharField(default='USDC', max_length=225),
        ),
    ]
